-- ============================================================================
--  AU FACEIT Bot — Supabase schema (tables + critical Postgres functions)
--  ---------------------------------------------------------------------------
--  Run this in the Supabase SQL editor (or via psql) once. It creates all the
--  tables the bot reads/writes through the REST API, plus the atomic RPC
--  functions used for the critical, multi-row operations.
-- ============================================================================

create extension if not exists "pgcrypto";

-- ---------------------------------------------------------------------------
--  Guilds
-- ---------------------------------------------------------------------------
create table if not exists public.guilds (
  id          bigint primary key,          -- Discord guild id
  enabled     boolean not null default true,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

create table if not exists public.guild_settings (
  guild_id              bigint primary key references public.guilds(id) on delete cascade,
  admin_role_id         bigint,
  moderator_role_id     bigint,
  registered_role_id    bigint,
  register_channel_id   bigint,
  register_message_id   bigint,
  queue_channel_id      bigint,
  queue_message_id      bigint,
  leaderboard_channel_id bigint,
  leaderboard_message_id bigint,
  match_category_id     bigint,
  log_channel_id        bigint,
  default_elo           integer not null default 1000,
  win_elo               integer not null default 8,
  loss_elo              integer not null default -6,
  queue_size            integer not null default 15,
  nickname_format       text,
  cleanup_match_channels boolean not null default true,
  created_at            timestamptz not null default now(),
  updated_at            timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
--  Players
-- ---------------------------------------------------------------------------
create table if not exists public.players (
  id                 bigint generated by default as identity primary key,
  guild_id           bigint not null references public.guilds(id) on delete cascade,
  discord_user_id    bigint not null,
  among_us_name      varchar(100) not null,
  nickname           text,
  faceit_player_id   varchar(64),
  faceit_nickname    varchar(100),
  elo                integer not null default 1000,
  peak_elo           integer not null default 1000,
  level              integer not null default 1,
  matches            integer not null default 0,
  wins               integer not null default 0,
  losses             integer not null default 0,
  win_streak         integer not null default 0,
  best_win_streak    integer not null default 0,
  total_voice_seconds bigint not null default 0,
  registered_at      timestamptz not null default now(),
  active             boolean not null default true,
  banned             boolean not null default false,
  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now(),
  constraint uq_players_guild_user    unique (guild_id, discord_user_id),
  constraint uq_players_guild_amongus unique (guild_id, among_us_name)
);
create index if not exists idx_players_guild on public.players(guild_id);
create index if not exists idx_players_discord on public.players(discord_user_id);

-- ---------------------------------------------------------------------------
--  Levels
-- ---------------------------------------------------------------------------
create table if not exists public.level_roles (
  id        bigint generated by default as identity primary key,
  guild_id  bigint not null references public.guilds(id) on delete cascade,
  level     integer not null,
  min_elo   integer,
  max_elo   integer,
  role_id   bigint,
  constraint uq_level_roles_guild_level unique (guild_id, level)
);
create index if not exists idx_level_roles_guild on public.level_roles(guild_id);

-- ---------------------------------------------------------------------------
--  Queue
-- ---------------------------------------------------------------------------
create table if not exists public.queue_entries (
  id               bigint generated by default as identity primary key,
  guild_id         bigint not null references public.guilds(id) on delete cascade,
  player_id        bigint not null references public.players(id) on delete cascade,
  joined_at        timestamptz not null default now(),
  queue_position   integer,
  status           varchar(20) not null default 'WAITING',
  constraint uq_queue_guild_player unique (guild_id, player_id, status)
);
create index if not exists idx_queue_guild_status on public.queue_entries(guild_id, status);

-- ---------------------------------------------------------------------------
--  Matches
-- ---------------------------------------------------------------------------
create sequence if not exists public.match_display_seq start 1;

create table if not exists public.matches (
  id                   bigint generated by default as identity primary key,
  guild_id             bigint not null references public.guilds(id) on delete cascade,
  display_id           varchar(32) not null unique,
  status               varchar(20) not null default 'CREATING',
  created_at           timestamptz not null default now(),
  started_at           timestamptz,
  finished_at          timestamptz,
  text_channel_id      bigint,
  voice_channel_id     bigint,
  average_elo          integer,
  winner_side          varchar(20),
  result_submitted_by  bigint,
  result_approved_by   bigint,
  result_processed     boolean not null default false
);
create index if not exists idx_matches_guild_status on public.matches(guild_id, status);

create table if not exists public.elo_transactions (
  id               bigint generated by default as identity primary key,
  guild_id         bigint not null references public.guilds(id) on delete cascade,
  player_id        bigint not null references public.players(id) on delete cascade,
  match_id         bigint references public.matches(id) on delete set null,
  old_elo          integer not null,
  change           integer not null,
  new_elo          integer not null,
  reason           varchar(100),
  transaction_type varchar(32) not null default 'MATCH',
  created_by       bigint,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now(),
  constraint uq_elo_tx_match_player_type unique (match_id, player_id, transaction_type)
);
create index if not exists idx_elo_player on public.elo_transactions(player_id);

create table if not exists public.match_players (
  id           bigint generated by default as identity primary key,
  match_id     bigint not null references public.matches(id) on delete cascade,
  player_id    bigint not null references public.players(id) on delete cascade,
  call_number  integer not null,
  role_side    varchar(20),
  elo_before   integer,
  elo_delta    integer,
  elo_after    integer,
  result       varchar(20),
  constraint uq_match_players_match_player unique (match_id, player_id),
  constraint uq_match_players_match_call  unique (match_id, call_number)
);
create index if not exists idx_match_players_match on public.match_players(match_id);

create table if not exists public.match_results (
  id            bigint generated by default as identity primary key,
  match_id      bigint not null unique references public.matches(id) on delete cascade,
  winner_side   varchar(20) not null,
  screenshot_url text,
  submitted_by  bigint not null,
  approved_by   bigint,
  submitted_at  timestamptz not null default now(),
  approved_at   timestamptz
);

create table if not exists public.result_submissions (
  id                  bigint generated by default as identity primary key,
  match_id            bigint not null references public.matches(id) on delete cascade,
  guild_id            bigint not null references public.guilds(id) on delete cascade,
  submitted_by        bigint not null,
  winner_side         varchar(20) not null,
  impostor_player_ids text not null,
  screenshot_url      text,
  approval_message_id bigint,
  status              varchar(20) not null default 'PENDING',
  submitted_at        timestamptz not null default now(),
  approved_by         bigint,
  approved_at         timestamptz,
  rejected_by         bigint,
  rejected_at         timestamptz,
  rejection_reason    text
);
create index if not exists idx_result_submissions_match on public.result_submissions(match_id);

-- ---------------------------------------------------------------------------
--  Voice
-- ---------------------------------------------------------------------------
create table if not exists public.voice_sessions (
  id               bigint generated by default as identity primary key,
  guild_id         bigint not null references public.guilds(id) on delete cascade,
  player_id        bigint not null references public.players(id) on delete cascade,
  channel_id       bigint not null,
  joined_at        timestamptz not null default now(),
  left_at          timestamptz,
  duration_seconds integer
);
create index if not exists idx_voice_open on public.voice_sessions(guild_id, player_id) where left_at is null;

create table if not exists public.voice_totals (
  id            bigint generated by default as identity primary key,
  guild_id      bigint not null references public.guilds(id) on delete cascade,
  player_id     bigint not null references public.players(id) on delete cascade,
  bucket_date   date not null,
  total_seconds bigint not null default 0,
  constraint uq_voice_totals_bucket unique (guild_id, player_id, bucket_date)
);

-- ---------------------------------------------------------------------------
--  Panels / Audit / Bans / Cooldowns
-- ---------------------------------------------------------------------------
create table if not exists public.panels (
  id                 bigint generated by default as identity primary key,
  guild_id           bigint not null references public.guilds(id) on delete cascade,
  type               varchar(32) not null,
  channel_id         bigint,
  message_id         bigint,
  title              varchar(200),
  description        text,
  color              integer,
  thumbnail_url      text,
  image_url          text,
  footer             varchar(200),
  configuration_json text
);
create index if not exists idx_panels_guild on public.panels(guild_id);

create table if not exists public.audit_logs (
  id            bigint generated by default as identity primary key,
  guild_id      bigint not null references public.guilds(id) on delete cascade,
  action_type   varchar(30) not null,
  actor_id      bigint,
  target_entity varchar(50),
  details       text,
  success       boolean not null default true,
  error_message text,
  created_at    timestamptz not null default now()
);
create index if not exists idx_audit_guild on public.audit_logs(guild_id);

create table if not exists public.bans (
  id         bigint generated by default as identity primary key,
  guild_id   bigint not null references public.guilds(id) on delete cascade,
  player_id  bigint not null references public.players(id) on delete cascade,
  reason     text,
  banned_by  bigint,
  active     boolean not null default true,
  banned_at  timestamptz not null default now(),
  unbanned_at timestamptz
);

create table if not exists public.cooldowns (
  id         bigint generated by default as identity primary key,
  guild_id   bigint not null references public.guilds(id) on delete cascade,
  user_id    bigint not null,
  action     varchar(32) not null,
  expires_at timestamptz not null
);

-- ============================================================================
--  CRITICAL ATOMIC RPC FUNCTIONS
-- ============================================================================

-- pop_queue_entries: atomically read and clear all WAITING entries for a guild.
create or replace function public.pop_queue_entries(p_guild_id bigint)
returns bigint[]
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_ids bigint[];
begin
  select array_agg(player_id) into v_ids
    from public.queue_entries
   where guild_id = p_guild_id and status = 'WAITING';

  delete from public.queue_entries
   where guild_id = p_guild_id and status = 'WAITING';

  return coalesce(v_ids, '{}');
end;
$$;

-- claim_match_from_queue: lock exactly one configured match worth of eligible
-- players, create the match and its player rows, then remove only those queue
-- rows. If the queue is not full, no rows are changed.
create or replace function public.claim_match_from_queue(p_guild_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_queue_size integer;
  v_ids bigint[];
  v_match public.matches%rowtype;
  v_seq bigint;
  v_elo integer;
  v_sum integer := 0;
  v_count integer := 0;
  v_pid bigint;
begin
  select gs.queue_size
    into v_queue_size
    from public.guild_settings as gs
   where gs.guild_id = p_guild_id;

  if v_queue_size is null or v_queue_size < 1 then
    raise exception 'Valid guild settings not found for guild %', p_guild_id;
  end if;

  select array_agg(claimed.player_id order by claimed.joined_at, claimed.id)
    into v_ids
    from (
      select q.id, q.player_id, q.joined_at
        from public.queue_entries as q
        join public.players as p
          on p.id = q.player_id
         and p.guild_id = q.guild_id
       where q.guild_id = p_guild_id
         and q.status = 'WAITING'
         and p.active = true
         and p.banned = false
       order by q.joined_at, q.id
       limit v_queue_size
       for update of q skip locked
    ) as claimed;

  if cardinality(coalesce(v_ids, '{}'::bigint[])) < v_queue_size then
    return null;
  end if;

  v_seq := nextval('public.match_display_seq');
  insert into public.matches (guild_id, display_id, status)
  values (p_guild_id, format('AU-%08s', v_seq), 'CREATING')
  returning * into v_match;

  for v_pid in select unnest(v_ids) order by random()
  loop
    select p.elo
      into strict v_elo
      from public.players as p
     where p.id = v_pid
       and p.guild_id = p_guild_id
       and p.active = true
       and p.banned = false;
    v_sum := v_sum + v_elo;
    v_count := v_count + 1;
    insert into public.match_players (match_id, player_id, call_number, elo_before)
    values (v_match.id, v_pid, v_count, v_elo);
  end loop;

  delete from public.queue_entries as q
   where q.guild_id = p_guild_id
     and q.status = 'WAITING'
     and q.player_id = any(v_ids);

  update public.matches
     set average_elo = v_sum / v_count
   where id = v_match.id
  returning * into v_match;

  return jsonb_build_object(
    'match', to_jsonb(v_match),
    'player_ids', to_jsonb(v_ids)
  );
end;
$$;

-- create_match: create a match + its players with CALL numbers in one transaction.
create or replace function public.create_match(p_guild_id bigint, p_player_ids jsonb)
returns setof public.matches
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_match public.matches%rowtype;
  v_seq bigint;
  v_elo integer;
  v_sum integer := 0;
  v_count integer := 0;
  v_pid bigint;
begin
  v_seq := nextval('public.match_display_seq');

  insert into public.matches (guild_id, display_id, status)
  values (p_guild_id, format('AU-%08s', v_seq), 'CREATING')
  returning * into v_match;

  for v_pid in select value::bigint from jsonb_array_elements_text(p_player_ids)
  loop
    select elo into v_elo from public.players where id = v_pid;
    v_elo := coalesce(v_elo, 1000);
    v_sum := v_sum + v_elo;
    v_count := v_count + 1;
    insert into public.match_players (match_id, player_id, call_number, elo_before)
    values (v_match.id, v_pid, v_count, v_elo);
  end loop;

  if v_count > 0 then
    update public.matches set average_elo = v_sum / v_count where id = v_match.id;
    v_match.average_elo := v_sum / v_count;
  end if;

  return next v_match;
end;
$$;

-- apply_match_result: settle Elo for every player + write transactions atomically.
-- p_players is a jsonb array of {player_id, elo_before, role_side}.
create or replace function public.apply_match_result(
  p_guild_id    bigint,
  p_players     jsonb,
  p_winner_side text,
  p_win_delta   integer,
  p_loss_delta  integer,
  p_match_id    bigint,
  p_approved_by bigint
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_item jsonb;
  v_pid bigint;
  v_role text;
  v_before integer;
  v_delta integer;
  v_after integer;
  v_peak integer;
begin
  for v_item in select * from jsonb_array_elements(p_players)
  loop
    v_pid := (v_item->>'player_id')::bigint;
    v_role := v_item->>'role_side';
    v_before := coalesce((v_item->>'elo_before')::integer, 1000);
    v_delta := case when v_role = p_winner_side then p_win_delta else p_loss_delta end;
    v_after := v_before + v_delta;

    update public.players
       set elo = v_after,
           peak_elo = greatest(peak_elo, v_after),
           updated_at = now()
     where id = v_pid;

    select peak_elo into v_peak from public.players where id = v_pid;
    v_peak := greatest(v_peak, v_after);
    update public.players set peak_elo = v_peak where id = v_pid;

    insert into public.elo_transactions
      (guild_id, player_id, match_id, old_elo, change, new_elo, reason, created_by)
    values (p_guild_id, v_pid, p_match_id, v_before, v_delta, v_after,
            format('Match %s', p_winner_side), p_approved_by);
  end loop;
end;
$$;

-- submit_match_result: verify guild/status/impostors, insert a PENDING submission
-- and mark the match awaiting approval. A partial unique index guarantees at most
-- one PENDING submission per match.
create unique index if not exists uq_result_submissions_pending_match
  on public.result_submissions(match_id)
  where status = 'PENDING';

create or replace function public.submit_match_result(
  p_guild_id            bigint,
  p_match_id            bigint,
  p_submitted_by        bigint,
  p_winner_side         text,
  p_impostor_player_ids jsonb,
  p_screenshot_url      text
)
returns setof public.result_submissions
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_sub public.result_submissions%rowtype;
  v_match public.matches%rowtype;
  v_impostor_id bigint;
begin
  if p_winner_side not in ('CREWMATE', 'IMPOSTOR') then
    raise exception 'Invalid winner side';
  end if;
  if p_screenshot_url is null or btrim(p_screenshot_url) = '' then
    raise exception 'Screenshot is required';
  end if;
  if p_impostor_player_ids is null
     or jsonb_typeof(p_impostor_player_ids) <> 'array' then
    raise exception 'Impostor players must be a JSON array';
  end if;
  if jsonb_array_length(p_impostor_player_ids) not between 1 and 3 then
    raise exception 'Impostor player count must be between 1 and 3';
  end if;
  if jsonb_array_length(p_impostor_player_ids) <>
     (select count(distinct value) from jsonb_array_elements_text(p_impostor_player_ids)) then
    raise exception 'Impostor players must be unique';
  end if;

  select * into v_match from public.matches
   where id = p_match_id and guild_id = p_guild_id
   for update;
  if not found then
    raise exception 'Match not found in guild';
  end if;
  if v_match.result_processed or v_match.status not in ('READY', 'IN_PROGRESS') then
    raise exception 'Match does not accept result submissions';
  end if;
  if not exists (
    select 1 from public.match_players mp
    join public.players p on p.id = mp.player_id
    where mp.match_id = p_match_id and p.discord_user_id = p_submitted_by
  ) then
    raise exception 'Submitter is not a match player';
  end if;

  for v_impostor_id in
    select distinct value::bigint from jsonb_array_elements_text(p_impostor_player_ids)
  loop
    if not exists (
      select 1 from public.match_players
      where match_id = p_match_id and player_id = v_impostor_id
    ) then
      raise exception 'Impostor player % is not in match', v_impostor_id;
    end if;
  end loop;

  insert into public.result_submissions
    (guild_id, match_id, submitted_by, winner_side, impostor_player_ids, screenshot_url)
  values (
    p_guild_id,
    p_match_id,
    p_submitted_by,
    p_winner_side,
    coalesce((select string_agg(value, ',' order by value)
      from jsonb_array_elements_text(p_impostor_player_ids)), ''),
    p_screenshot_url
  ) returning * into v_sub;

  update public.matches
     set status = 'RESULT_PENDING', result_submitted_by = p_submitted_by
   where id = p_match_id;
  return next v_sub;
end;
$$;

-- approve_match_result: settle Elo, player stats and transactions atomically.
create or replace function public.approve_match_result(
  p_match_id    bigint,
  p_approved_by bigint,
  p_win_elo     integer,
  p_loss_elo    integer
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_sub public.result_submissions%rowtype;
  v_match public.matches%rowtype;
  v_mp public.match_players%rowtype;
  v_player public.players%rowtype;
  v_impostors bigint[] := '{}'::bigint[];
  v_role text;
  v_delta integer;
  v_after integer;
  v_won boolean;
begin
  select * into v_sub from public.result_submissions
   where match_id = p_match_id and status = 'PENDING'
   order by id limit 1 for update;
  if not found then
    raise exception 'No pending result submission for match %', p_match_id;
  end if;

  select * into v_match from public.matches where id = p_match_id for update;
  if not found or v_match.result_processed then
    raise exception 'Match missing or already processed';
  end if;

  if nullif(v_sub.impostor_player_ids, '') is not null then
    select array_agg(value::bigint) into v_impostors
      from unnest(string_to_array(v_sub.impostor_player_ids, ',')) value;
  end if;

  for v_mp in
    select * from public.match_players where match_id = p_match_id order by id for update
  loop
    select * into strict v_player from public.players
     where id = v_mp.player_id and guild_id = v_match.guild_id for update;
    v_role := case when v_mp.player_id = any(v_impostors)
                   then 'IMPOSTOR' else 'CREWMATE' end;
    v_won := v_role = v_sub.winner_side;
    v_delta := case when v_won then p_win_elo else p_loss_elo end;
    v_after := v_player.elo + v_delta;

    update public.players
       set elo = v_after,
           peak_elo = greatest(peak_elo, v_after),
           matches = matches + 1,
           wins = wins + case when v_won then 1 else 0 end,
           losses = losses + case when v_won then 0 else 1 end,
           win_streak = case when v_won then win_streak + 1 else 0 end,
           best_win_streak = case when v_won
             then greatest(best_win_streak, win_streak + 1) else best_win_streak end,
           updated_at = now()
     where id = v_player.id;

    update public.match_players
       set role_side = v_role,
           elo_before = v_player.elo,
           elo_delta = v_delta,
           elo_after = v_after,
           result = case when v_won then 'WIN' else 'LOSS' end
     where id = v_mp.id;

    insert into public.elo_transactions
      (guild_id, player_id, match_id, old_elo, change, new_elo, reason,
       transaction_type, created_by)
    values
      (v_match.guild_id, v_player.id, p_match_id, v_player.elo, v_delta, v_after,
       format('Match %s', v_sub.winner_side), 'MATCH', p_approved_by);
  end loop;

  insert into public.match_results
    (match_id, winner_side, screenshot_url, submitted_by, approved_by, approved_at)
  values
    (p_match_id, v_sub.winner_side, v_sub.screenshot_url,
     v_sub.submitted_by, p_approved_by, now());

  update public.result_submissions
     set status = 'APPROVED', approved_by = p_approved_by, approved_at = now()
   where id = v_sub.id;
  update public.matches
     set status = 'COMPLETED', winner_side = v_sub.winner_side,
         result_processed = true, result_approved_by = p_approved_by,
         finished_at = now()
   where id = p_match_id;
end;
$$;

-- reject_match_result: reject a PENDING submission and reopen the match,
-- recording the rejecting moderator, timestamp and an optional reason.
create or replace function public.reject_match_result(
  p_match_id    bigint,
  p_rejected_by bigint,
  p_reason      text default null
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_sub public.result_submissions%rowtype;
  v_match public.matches%rowtype;
begin
  select * into v_sub from public.result_submissions
   where match_id = p_match_id and status = 'PENDING'
   order by id limit 1 for update;
  if not found then
    raise exception 'No pending result submission for match %', p_match_id;
  end if;

  select * into v_match from public.matches where id = p_match_id for update;
  if not found then
    raise exception 'Match missing for result rejection';
  end if;
  if v_match.result_processed then
    raise exception 'Match is already processed';
  end if;

  update public.result_submissions
     set status = 'REJECTED',
         rejected_by = p_rejected_by,
         rejected_at = now(),
         rejection_reason = nullif(btrim(coalesce(p_reason, '')), ''),
         approved_by = null,
         approved_at = null
   where id = v_sub.id;

  update public.matches
     set status = 'IN_PROGRESS', result_submitted_by = null
   where id = p_match_id;
end;
$$;

-- The bot is the only database client. Keep all exposed tables behind RLS and
-- grant Data API access exclusively to the server-side service_role.
alter table public.guilds enable row level security;
alter table public.guild_settings enable row level security;
alter table public.players enable row level security;
alter table public.level_roles enable row level security;
alter table public.queue_entries enable row level security;
alter table public.matches enable row level security;
alter table public.elo_transactions enable row level security;
alter table public.match_players enable row level security;
alter table public.match_results enable row level security;
alter table public.result_submissions enable row level security;
alter table public.voice_sessions enable row level security;
alter table public.voice_totals enable row level security;
alter table public.panels enable row level security;
alter table public.audit_logs enable row level security;
alter table public.bans enable row level security;
alter table public.cooldowns enable row level security;

revoke all on all tables in schema public from anon, authenticated;
revoke all on all sequences in schema public from anon, authenticated;
grant select, insert, update, delete on all tables in schema public to service_role;
grant usage, select on all sequences in schema public to service_role;

revoke execute on function public.pop_queue_entries(bigint) from public, anon, authenticated;
revoke execute on function public.claim_match_from_queue(bigint) from public, anon, authenticated;
revoke execute on function public.create_match(bigint, jsonb) from public, anon, authenticated;
revoke execute on function public.apply_match_result(bigint, jsonb, text, integer, integer, bigint, bigint) from public, anon, authenticated;
revoke execute on function public.submit_match_result(bigint, bigint, bigint, text, jsonb, text) from public, anon, authenticated;
revoke execute on function public.approve_match_result(bigint, bigint, integer, integer) from public, anon, authenticated;
-- Legacy 2-argument reject overload (created by an early migration) is removed
-- so fresh and migrated databases end in the same, single 3-argument signature.
drop function if exists public.reject_match_result(bigint, bigint);
revoke execute on function public.reject_match_result(bigint, bigint, text) from public, anon, authenticated;

grant execute on function public.pop_queue_entries(bigint) to service_role;
grant execute on function public.claim_match_from_queue(bigint) to service_role;
grant execute on function public.create_match(bigint, jsonb) to service_role;
grant execute on function public.apply_match_result(bigint, jsonb, text, integer, integer, bigint, bigint) to service_role;
grant execute on function public.submit_match_result(bigint, bigint, bigint, text, jsonb, text) to service_role;
grant execute on function public.approve_match_result(bigint, bigint, integer, integer) to service_role;
grant execute on function public.reject_match_result(bigint, bigint, text) to service_role;
