-- ============================================================================
--  AU FACEIT Bot — Supabase schema (tables + critical Postgres functions)
--  ---------------------------------------------------------------------------
--  Run this in the Supabase SQL editor (or via psql) once. It creates all the
--  tables the bot reads/writes through the REST API, plus the atomic RPC
--  functions used for the critical, multi-row operations.
-- ============================================================================

create extension if not exists "pgcrypto";

-- ---------------------------------------------------------------------------
--  Guilds
-- ---------------------------------------------------------------------------
create table if not exists public.guilds (
  id          bigint primary key,          -- Discord guild id
  enabled     boolean not null default true,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

create table if not exists public.guild_settings (
  guild_id              bigint primary key references public.guilds(id) on delete cascade,
  admin_role_id         bigint,
  moderator_role_id     bigint,
  registered_role_id    bigint,
  register_channel_id   bigint,
  register_message_id   bigint,
  queue_channel_id      bigint,
  queue_message_id      bigint,
  leaderboard_channel_id bigint,
  leaderboard_message_id bigint,
  match_category_id     bigint,
  log_channel_id        bigint,
  default_elo           integer not null default 1000,
  win_elo               integer not null default 8,
  loss_elo              integer not null default -6,
  queue_size            integer not null default 15,
  nickname_format       text,
  created_at            timestamptz not null default now(),
  updated_at            timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
--  Players
-- ---------------------------------------------------------------------------
create table if not exists public.players (
  id                 bigint generated by default as identity primary key,
  guild_id           bigint not null references public.guilds(id) on delete cascade,
  discord_user_id    bigint not null,
  among_us_name      varchar(100) not null,
  nickname           text,
  faceit_player_id   varchar(64),
  faceit_nickname    varchar(100),
  elo                integer not null default 1000,
  peak_elo           integer not null default 1000,
  level              integer not null default 1,
  matches            integer not null default 0,
  wins               integer not null default 0,
  losses             integer not null default 0,
  win_streak         integer not null default 0,
  best_win_streak    integer not null default 0,
  total_voice_seconds bigint not null default 0,
  registered_at      timestamptz not null default now(),
  active             boolean not null default true,
  banned             boolean not null default false,
  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now(),
  constraint uq_players_guild_user    unique (guild_id, discord_user_id),
  constraint uq_players_guild_amongus unique (guild_id, among_us_name)
);
create index if not exists idx_players_guild on public.players(guild_id);
create index if not exists idx_players_discord on public.players(discord_user_id);

create table if not exists public.elo_transactions (
  id               bigint generated by default as identity primary key,
  guild_id         bigint not null references public.guilds(id) on delete cascade,
  player_id        bigint not null references public.players(id) on delete cascade,
  match_id         bigint references public.matches(id) on delete set null,
  old_elo          integer not null,
  change           integer not null,
  new_elo          integer not null,
  reason           varchar(100),
  transaction_type varchar(32) not null default 'MATCH',
  created_by       bigint,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now(),
  constraint uq_elo_tx_match_player_type unique (match_id, player_id, transaction_type)
);
create index if not exists idx_elo_player on public.elo_transactions(player_id);

-- ---------------------------------------------------------------------------
--  Levels
-- ---------------------------------------------------------------------------
create table if not exists public.level_roles (
  id        bigint generated by default as identity primary key,
  guild_id  bigint not null references public.guilds(id) on delete cascade,
  level     integer not null,
  min_elo   integer,
  max_elo   integer,
  role_id   bigint,
  constraint uq_level_roles_guild_level unique (guild_id, level)
);
create index if not exists idx_level_roles_guild on public.level_roles(guild_id);

-- ---------------------------------------------------------------------------
--  Queue
-- ---------------------------------------------------------------------------
create table if not exists public.queue_entries (
  id               bigint generated by default as identity primary key,
  guild_id         bigint not null references public.guilds(id) on delete cascade,
  player_id        bigint not null references public.players(id) on delete cascade,
  joined_at        timestamptz not null default now(),
  queue_position   integer,
  status           varchar(20) not null default 'WAITING',
  constraint uq_queue_guild_player unique (guild_id, player_id, status)
);
create index if not exists idx_queue_guild_status on public.queue_entries(guild_id, status);

-- ---------------------------------------------------------------------------
--  Matches
-- ---------------------------------------------------------------------------
create sequence if not exists public.match_display_seq start 1;

create table if not exists public.matches (
  id                   bigint generated by default as identity primary key,
  guild_id             bigint not null references public.guilds(id) on delete cascade,
  display_id           varchar(32) not null unique,
  status               varchar(20) not null default 'CREATING',
  created_at           timestamptz not null default now(),
  started_at           timestamptz,
  finished_at          timestamptz,
  text_channel_id      bigint,
  voice_channel_id     bigint,
  average_elo          integer,
  winner_side          varchar(20),
  result_submitted_by  bigint,
  result_approved_by   bigint,
  result_processed     boolean not null default false
);
create index if not exists idx_matches_guild_status on public.matches(guild_id, status);

create table if not exists public.match_players (
  id           bigint generated by default as identity primary key,
  match_id     bigint not null references public.matches(id) on delete cascade,
  player_id    bigint not null references public.players(id) on delete cascade,
  call_number  integer not null,
  role_side    varchar(20),
  elo_before   integer,
  elo_delta    integer,
  elo_after    integer,
  result       varchar(20),
  constraint uq_match_players_match_player unique (match_id, player_id),
  constraint uq_match_players_match_call  unique (match_id, call_number)
);
create index if not exists idx_match_players_match on public.match_players(match_id);

create table if not exists public.match_results (
  id            bigint generated by default as identity primary key,
  match_id      bigint not null unique references public.matches(id) on delete cascade,
  winner_side   varchar(20) not null,
  screenshot_url text,
  submitted_by  bigint not null,
  approved_by   bigint,
  submitted_at  timestamptz not null default now(),
  approved_at   timestamptz
);

create table if not exists public.result_submissions (
  id                  bigint generated by default as identity primary key,
  match_id            bigint not null references public.matches(id) on delete cascade,
  guild_id            bigint not null references public.guilds(id) on delete cascade,
  submitted_by        bigint not null,
  winner_side         varchar(20) not null,
  impostor_player_ids text not null,
  screenshot_url      text,
  status              varchar(20) not null default 'PENDING',
  submitted_at        timestamptz not null default now(),
  approved_by         bigint,
  approved_at         timestamptz
);
create index if not exists idx_result_submissions_match on public.result_submissions(match_id);

-- ---------------------------------------------------------------------------
--  Voice
-- ---------------------------------------------------------------------------
create table if not exists public.voice_sessions (
  id               bigint generated by default as identity primary key,
  guild_id         bigint not null references public.guilds(id) on delete cascade,
  player_id        bigint not null references public.players(id) on delete cascade,
  channel_id       bigint not null,
  joined_at        timestamptz not null default now(),
  left_at          timestamptz,
  duration_seconds integer
);
create index if not exists idx_voice_open on public.voice_sessions(guild_id, player_id) where left_at is null;

create table if not exists public.voice_totals (
  id            bigint generated by default as identity primary key,
  guild_id      bigint not null references public.guilds(id) on delete cascade,
  player_id     bigint not null references public.players(id) on delete cascade,
  bucket_date   date not null,
  total_seconds bigint not null default 0,
  constraint uq_voice_totals_bucket unique (guild_id, player_id, bucket_date)
);

-- ---------------------------------------------------------------------------
--  Panels / Audit / Bans / Cooldowns
-- ---------------------------------------------------------------------------
create table if not exists public.panels (
  id                 bigint generated by default as identity primary key,
  guild_id           bigint not null references public.guilds(id) on delete cascade,
  type               varchar(32) not null,
  channel_id         bigint,
  message_id         bigint,
  title              varchar(200),
  description        text,
  color              integer,
  thumbnail_url      text,
  image_url          text,
  footer             varchar(200),
  configuration_json text
);
create index if not exists idx_panels_guild on public.panels(guild_id);

create table if not exists public.audit_logs (
  id            bigint generated by default as identity primary key,
  guild_id      bigint not null references public.guilds(id) on delete cascade,
  action_type   varchar(30) not null,
  actor_id      bigint,
  target_entity varchar(50),
  details       text,
  success       boolean not null default true,
  error_message text,
  created_at    timestamptz not null default now()
);
create index if not exists idx_audit_guild on public.audit_logs(guild_id);

create table if not exists public.bans (
  id         bigint generated by default as identity primary key,
  guild_id   bigint not null references public.guilds(id) on delete cascade,
  player_id  bigint not null references public.players(id) on delete cascade,
  reason     text,
  banned_by  bigint,
  active     boolean not null default true,
  banned_at  timestamptz not null default now(),
  unbanned_at timestamptz
);

create table if not exists public.cooldowns (
  id         bigint generated by default as identity primary key,
  guild_id   bigint not null references public.guilds(id) on delete cascade,
  user_id    bigint not null,
  action     varchar(32) not null,
  expires_at timestamptz not null
);

-- ============================================================================
--  CRITICAL ATOMIC RPC FUNCTIONS
-- ============================================================================

-- pop_queue_entries: atomically read and clear all WAITING entries for a guild.
create or replace function public.pop_queue_entries(p_guild_id bigint)
returns bigint[]
language plpgsql
security definer
set search_path = public
as $$
declare
  v_ids bigint[];
begin
  select array_agg(player_id) into v_ids
    from public.queue_entries
   where guild_id = p_guild_id and status = 'WAITING';

  delete from public.queue_entries
   where guild_id = p_guild_id and status = 'WAITING';

  return coalesce(v_ids, '{}');
end;
$$;

-- create_match: create a match + its players with CALL numbers in one transaction.
create or replace function public.create_match(p_guild_id bigint, p_player_ids jsonb)
returns setof public.matches
language plpgsql
security definer
set search_path = public
as $$
declare
  v_match public.matches%rowtype;
  v_seq bigint;
  v_elo integer;
  v_sum integer := 0;
  v_count integer := 0;
  v_pid bigint;
begin
  v_seq := nextval('public.match_display_seq');

  insert into public.matches (guild_id, display_id, status)
  values (p_guild_id, format('AU-%08s', v_seq), 'CREATING')
  returning * into v_match;

  for v_pid in select value::bigint from jsonb_array_elements_text(p_player_ids)
  loop
    select elo into v_elo from public.players where id = v_pid;
    v_elo := coalesce(v_elo, 1000);
    v_sum := v_sum + v_elo;
    v_count := v_count + 1;
    insert into public.match_players (match_id, player_id, call_number, elo_before)
    values (v_match.id, v_pid, v_count, v_elo);
  end loop;

  if v_count > 0 then
    update public.matches set average_elo = v_sum / v_count where id = v_match.id;
    v_match.average_elo := v_sum / v_count;
  end if;

  return next v_match;
end;
$$;

-- apply_match_result: settle Elo for every player + write transactions atomically.
-- p_players is a jsonb array of {player_id, elo_before, role_side}.
create or replace function public.apply_match_result(
  p_guild_id    bigint,
  p_players     jsonb,
  p_winner_side text,
  p_win_delta   integer,
  p_loss_delta  integer,
  p_match_id    bigint,
  p_approved_by bigint
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_item jsonb;
  v_pid bigint;
  v_role text;
  v_before integer;
  v_delta integer;
  v_after integer;
  v_peak integer;
begin
  for v_item in select * from jsonb_array_elements(p_players)
  loop
    v_pid := (v_item->>'player_id')::bigint;
    v_role := v_item->>'role_side';
    v_before := coalesce((v_item->>'elo_before')::integer, 1000);
    v_delta := case when v_role = p_winner_side then p_win_delta else p_loss_delta end;
    v_after := v_before + v_delta;

    update public.players
       set elo = v_after,
           peak_elo = greatest(peak_elo, v_after),
           updated_at = now()
     where id = v_pid;

    select peak_elo into v_peak from public.players where id = v_pid;
    v_peak := greatest(v_peak, v_after);
    update public.players set peak_elo = v_peak where id = v_pid;

    insert into public.elo_transactions
      (guild_id, player_id, match_id, old_elo, change, new_elo, reason, created_by)
    values (p_guild_id, v_pid, p_match_id, v_before, v_delta, v_after,
            format('Match %s', p_winner_side), p_approved_by);
  end loop;
end;
$$;

-- submit_match_result: insert a PENDING submission + mark the match awaiting approval.
create or replace function public.submit_match_result(
  p_guild_id            bigint,
  p_match_id            bigint,
  p_submitted_by        bigint,
  p_winner_side         text,
  p_impostor_player_ids jsonb,
  p_screenshot_url      text
)
returns setof public.result_submissions
language plpgsql
security definer
set search_path = public
as $$
declare
  v_sub public.result_submissions%rowtype;
begin
  insert into public.result_submissions
    (guild_id, match_id, submitted_by, winner_side, impostor_player_ids, screenshot_url)
  values (
    p_guild_id, p_match_id, p_submitted_by, p_winner_side,
    (select string_agg(value, ',' order by value) from jsonb_array_elements_text(p_impostor_player_ids)),
    p_screenshot_url
  )
  returning * into v_sub;

  update public.matches
     set status = 'RESULT_PENDING', result_submitted_by = p_submitted_by
   where id = p_match_id;

  return next v_sub;
end;
$$;

-- approve_match_result: settle Elo + finalize the match in one transaction.
create or replace function public.approve_match_result(
  p_match_id    bigint,
  p_approved_by bigint,
  p_win_elo     integer,
  p_loss_elo    integer
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_sub public.result_submissions%rowtype;
  v_match public.matches%rowtype;
  v_players jsonb := '[]'::jsonb;
  v_item jsonb;
  v_impostors bigint[];
  v_role text;
begin
  select * into v_sub from public.result_submissions
   where match_id = p_match_id and status = 'PENDING'
   order by id limit 1;
  if not found then
    raise exception 'No pending result submission for match %', p_match_id;
  end if;

  select * into v_match from public.matches where id = p_match_id;
  if not found then
    raise exception 'Match % not found', p_match_id;
  end if;

  select array_agg(x::bigint)
    into v_impostors
    from unnest(string_to_array(v_sub.impostor_player_ids, ',')) as x;

  for v_item in
    select jsonb_build_object(
      'player_id', mp.player_id,
      'elo_before', coalesce(mp.elo_before, p.elo),
      'role_side', v_role
    )
    from public.match_players mp
    join public.players p on p.id = mp.player_id
    where mp.match_id = p_match_id
  loop
    v_players := v_players || v_item;
  end loop;

  v_players := (
    select jsonb_agg(
      case when (e->>'player_id')::bigint = any(v_impostors)
           then jsonb_build_object('player_id', e->>'player_id', 'elo_before', e->>'elo_before', 'role_side', 'IMPOSTOR')
           else jsonb_build_object('player_id', e->>'player_id', 'elo_before', e->>'elo_before', 'role_side', 'CREWMATE')
      end
    )
    from jsonb_array_elements(v_players) e
  );

  perform public.apply_match_result(
    v_match.guild_id, v_players, v_sub.winner_side, p_win_elo, p_loss_elo, p_match_id, p_approved_by
  );

  update public.match_players
     set role_side = case when player_id = any(v_impostors) then 'IMPOSTOR' else 'CREWMATE' end
   where match_id = p_match_id;

  update public.result_submissions
     set status = 'APPROVED', approved_by = p_approved_by, approved_at = now()
   where id = v_sub.id;

  update public.matches
     set status = 'COMPLETED', winner_side = v_sub.winner_side,
         result_processed = true, result_approved_by = p_approved_by,
         finished_at = now()
   where id = p_match_id;
end;
$$;

-- Grant RPC execution to the roles used by the REST API.
grant execute on function public.pop_queue_entries(bigint) to anon, authenticated, service_role;
grant execute on function public.create_match(bigint, jsonb) to anon, authenticated, service_role;
grant execute on function public.apply_match_result(bigint, jsonb, text, integer, integer, bigint, bigint) to anon, authenticated, service_role;
grant execute on function public.submit_match_result(bigint, bigint, bigint, text, jsonb, text) to anon, authenticated, service_role;
grant execute on function public.approve_match_result(bigint, bigint, integer, integer) to anon, authenticated, service_role;

grant usage on sequence public.match_display_seq to anon, authenticated, service_role;
