"""Application-wide constants."""

CUSTOM_ID_SEP = ":"

MATCH_DISPLAY_PREFIX = "AU-"
MATCH_STATUS_CREATING = "CREATING"
MATCH_STATUS_READY = "READY"
MATCH_STATUS_IN_PROGRESS = "IN_PROGRESS"
MATCH_STATUS_RESULT_PENDING = "RESULT_PENDING"
MATCH_STATUS_COMPLETED = "COMPLETED"
MATCH_STATUS_CANCELLED = "CANCELLED"
MATCH_STATUS_DISPUTED = "DISPUTED"

QUEUE_STATUS_WAITING = "WAITING"
QUEUE_STATUS_LOCKED = "LOCKED"
QUEUE_STATUS_MATCHED = "MATCHED"
QUEUE_STATUS_LEFT = "LEFT"

SIDES_CREWMATE = "CREWMATE"
SIDES_IMPOSTOR = "IMPOSTOR"

LEVEL_COUNT = 10

# TOTAL_VOICE_BUCKET_PATHS (week / month bucketing)
BUCKET_WEEK = "week"
BUCKET_MONTH = "month"
